export default{
	optionsZonaHoraria:[   
	            {'label':'Adak', 'id':'America/Adak'},
	            {'label':'Anchorage', 'id':'America/Anchorage'},
	            {'label':'Anguilla', 'id':'America/Anguilla'},
	            {'label':'Antigua', 'id':'America/Antigua'},
	            {'label':'Araguaina', 'id':'America/Araguaina'},
	            {'label':'Argentina/Buenos Aires', 'id':'America/Argentina/Buenos_Aires'},
	            {'label':'Argentina/Catamarca', 'id':'America/Argentina/Catamarca'},
	            {'label':'Argentina/Cordoba', 'id':'America/Argentina/Cordoba'},
	            {'label':'Argentina/Jujuy', 'id':'America/Argentina/Jujuy'},
	            {'label':'Argentina/La Rioja', 'id':'America/Argentina/La_Rioja'},
	            {'label':'Argentina/Mendoza', 'id':'America/Argentina/Mendoza'},
	            {'label':'Argentina/Rio Gallegos', 'id':'America/Argentina/Rio_Gallegos'},
	            {'label':'Argentina/Salta', 'id':'America/Argentina/Salta'},
	            {'label':'Argentina/San Juan', 'id':'America/Argentina/San_Juan'},
	            {'label':'Argentina/San Luis', 'id':'America/Argentina/San_Luis'},
	            {'label':'Argentina/Tucuman', 'id':'America/Argentina/Tucuman'},
	            {'label':'Argentina/Ushuaia', 'id':'America/Argentina/Ushuaia'},
	            {'label':'Aruba', 'id':'America/Aruba'},
	            {'label':'Asuncion', 'id':'America/Asuncion'},
	            {'label':'Atikokan', 'id':'America/Atikokan'},
	            {'label':'Bahia', 'id':'America/Bahia'},
	            {'label':'Bahia Banderas', 'id':'America/Bahia_Banderas'},
	            {'label':'Barbados', 'id':'America/Barbados'},
	            {'label':'Belem', 'id':'America/Belem'},
	            {'label':'Belize', 'id':'America/Belize'},
	            {'label':'Blanc-Sablon', 'id':'America/Blanc-Sablon'},
	            {'label':'Boa Vista', 'id':'America/Boa_Vista'},
	            {'label':'Bogota', 'id':'America/Bogota'},
	            {'label':'Boise', 'id':'America/Boise'},
	            {'label':'Cambridge Bay', 'id':'America/Cambridge_Bay'},
	            {'label':'Campo Grande', 'id':'America/Campo_Grande'},
	            {'label':'Cancun', 'id':'America/Cancun'},
	            {'label':'Caracas', 'id':'America/Caracas'},
	            {'label':'Cayenne', 'id':'America/Cayenne'},
	            {'label':'Cayman', 'id':'America/Cayman'},
	            {'label':'Chicago', 'id':'America/Chicago'},
	            {'label':'Chihuahua', 'id':'America/Chihuahua'},
	            {'label':'Costa Rica', 'id':'America/Costa_Rica'},
	            {'label':'Creston', 'id':'America/Creston'},
	            {'label':'Cuiaba', 'id':'America/Cuiaba'},
	            {'label':'Curacao', 'id':'America/Curacao'},
	            {'label':'Danmarkshavn', 'id':'America/Danmarkshavn'},
	            {'label':'Dawson', 'id':'America/Dawson'},
	            {'label':'Dawson Creek', 'id':'America/Dawson_Creek'},
	            {'label':'Denver', 'id':'America/Denver'},
	            {'label':'Detroit', 'id':'America/Detroit'},
	            {'label':'Dominica', 'id':'America/Dominica'},
	            {'label':'Edmonton', 'id':'America/Edmonton'},
	            {'label':'Eirunepe', 'id':'America/Eirunepe'},
	            {'label':'El Salvador', 'id':'America/El_Salvador'},
	            {'label':'Fort Nelson', 'id':'America/Fort_Nelson'},
	            {'label':'Fortaleza', 'id':'America/Fortaleza'},
	            {'label':'Glace Bay', 'id':'America/Glace_Bay'},
	            {'label':'Godthab', 'id':'America/Godthab'},
	            {'label':'Goose Bay', 'id':'America/Goose_Bay'},
	            {'label':'Grand Turk', 'id':'America/Grand_Turk'},
	            {'label':'Grenada', 'id':'America/Grenada'},
	            {'label':'Guadeloupe', 'id':'America/Guadeloupe'},
	            {'label':'Guatemala', 'id':'America/Guatemala'},
	            {'label':'Guayaquil', 'id':'America/Guayaquil'},
	            {'label':'Guyana', 'id':'America/Guyana'},
	            {'label':'Halifax', 'id':'America/Halifax'},
	            {'label':'Havana', 'id':'America/Havana'},
	            {'label':'Hermosillo', 'id':'America/Hermosillo'},
	            {'label':'Indiana/Indianapolis', 'id':'America/Indiana/Indianapolis'},
	            {'label':'Indiana/Knox', 'id':'America/Indiana/Knox'},
	            {'label':'Indiana/Marengo', 'id':'America/Indiana/Marengo'},
	            {'label':'Indiana/Petersburg', 'id':'America/Indiana/Petersburg'},
	            {'label':'Indiana/Tell City', 'id':'America/Indiana/Tell_City'},
	            {'label':'Indiana/Vevay', 'id':'America/Indiana/Vevay'},
	            {'label':'Indiana/Vincennes', 'id':'America/Indiana/Vincennes'},
	            {'label':'Indiana/Winamac', 'id':'America/Indiana/Winamac'},
	            {'label':'Inuvik', 'id':'America/Inuvik'},
	            {'label':'Iqaluit', 'id':'America/Iqaluit'},
	            {'label':'Jamaica', 'id':'America/Jamaica'},
	            {'label':'Juneau', 'id':'America/Juneau'},
	            {'label':'Kentucky/Louisville', 'id':'America/Kentucky/Louisville'},
	            {'label':'Kentucky/Monticello', 'id':'America/Kentucky/Monticello'},
	            {'label':'Kralendijk', 'id':'America/Kralendijk'},
	            {'label':'La Paz', 'id':'America/La_Paz'},
	            {'label':'Lima', 'id':'America/Lima'},
	            {'label':'Los Angeles', 'id':'America/Los_Angeles'},
	            {'label':'Lower Princes', 'id':'America/Lower_Princes'},
	            {'label':'Maceio', 'id':'America/Maceio'},
	            {'label':'Managua', 'id':'America/Managua'},
	            {'label':'Manaus', 'id':'America/Manaus'},
	            {'label':'Marigot', 'id':'America/Marigot'},
	            {'label':'Martinique', 'id':'America/Martinique'},
	            {'label':'Matamoros', 'id':'America/Matamoros'},
	            {'label':'Mazatlan', 'id':'America/Mazatlan'},
	            {'label':'Menominee', 'id':'America/Menominee'},
	            {'label':'Merida', 'id':'America/Merida'},
	            {'label':'Metlakatla', 'id':'America/Metlakatla'},
	            {'label':'Mexico City', 'id':'America/Mexico_City'},
	            {'label':'Miquelon', 'id':'America/Miquelon'},
	            {'label':'Moncton', 'id':'America/Moncton'},
	            {'label':'Monterrey', 'id':'America/Monterrey'},
	            {'label':'Montevideo', 'id':'America/Montevideo'},
	            {'label':'Montserrat', 'id':'America/Montserrat'},
	            {'label':'Nassau', 'id':'America/Nassau'},
	            {'label':'New York', 'id':'America/New_York'},
	            {'label':'Nipigon', 'id':'America/Nipigon'},
	            {'label':'Nome', 'id':'America/Nome'},
	            {'label':'Noronha', 'id':'America/Noronha'},
	            {'label':'North Dakota/Beulah', 'id':'America/North_Dakota/Beulah'},
	            {'label':'North Dakota/Center', 'id':'America/North_Dakota/Center'},
	            {'label':'North Dakota/New Salem', 'id':'America/North_Dakota/New_Salem'},
	            {'label':'Ojinaga', 'id':'America/Ojinaga'},
	            {'label':'Panama', 'id':'America/Panama'},
	            {'label':'Pangnirtung', 'id':'America/Pangnirtung'},
	            {'label':'Paramaribo', 'id':'America/Paramaribo'},
	            {'label':'Phoenix', 'id':'America/Phoenix'},
	            {'label':'Port of Spain', 'id':'America/Port_of_Spain'},
	            {'label':'Port-au-Prince', 'id':'America/Port-au-Prince'},
	            {'label':'Porto Velho', 'id':'America/Porto_Velho'},
	            {'label':'Puerto Rico', 'id':'America/Puerto_Rico'},
	            {'label':'Punta Arenas', 'id':'America/Punta_Arenas'},
	            {'label':'Rainy River', 'id':'America/Rainy_River'},
	            {'label':'Rankin Inlet', 'id':'America/Rankin_Inlet'},
	            {'label':'Recife', 'id':'America/Recife'},
	            {'label':'Regina', 'id':'America/Regina'},
	            {'label':'Resolute', 'id':'America/Resolute'},
	            {'label':'Rio Branco', 'id':'America/Rio_Branco'},
	            {'label':'Santarem', 'id':'America/Santarem'},
	            {'label':'Santiago', 'id':'America/Santiago'},
	            {'label':'Santo Domingo', 'id':'America/Santo_Domingo'},
	            {'label':'Sao Paulo', 'id':'America/Sao_Paulo'},
	            {'label':'Scoresbysund', 'id':'America/Scoresbysund'},
	            {'label':'Sitka', 'id':'America/Sitka'},
	            {'label':'St Barthelemy', 'id':'America/St_Barthelemy'},
	            {'label':'St Johns', 'id':'America/St_Johns'},
	            {'label':'St Kitts', 'id':'America/St_Kitts'},
	            {'label':'St Lucia', 'id':'America/St_Lucia'},
	            {'label':'St Thomas', 'id':'America/St_Thomas'},
	            {'label':'St Vincent', 'id':'America/St_Vincent'},
	            {'label':'Swift Current', 'id':'America/Swift_Current'},
	            {'label':'Tegucigalpa', 'id':'America/Tegucigalpa'},
	            {'label':'Thule', 'id':'America/Thule'},
	            {'label':'Thunder Bay', 'id':'America/Thunder_Bay'},
	            {'label':'Tijuana', 'id':'America/Tijuana'},
	            {'label':'Toronto', 'id':'America/Toronto'},
	            {'label':'Tortola', 'id':'America/Tortola'},
	            {'label':'Vancouver', 'id':'America/Vancouver'},
	            {'label':'Whitehorse', 'id':'America/Whitehorse'},
	            {'label':'Winnipeg', 'id':'America/Winnipeg'},
	            {'label':'Yakutat', 'id':'America/Yakutat'},
	            {'label':'Yellowknife', 'id':'America/Yellowknife'},
	    	],
}